server:
  servlet:
    context-path: /eat

canal:
  host: 49.235.110.8
  port: 11111
#thymeleaf start
spring:
  redis:
        host: 127.0.0.1
        port: 6379
        password: 123456
        jedis:
          pool:
            max-active: 8
            max-wait: -1
            max-idle: 500
            min-idle: 0
        lettuce:
          shutdown-timeout: 0
#  profiles:
#    active: dev
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/lover?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: master
        password:
        name: master-datasource
        initialSize: 20
        maxActive: 60
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        timeBetweenEvictionRunsMillis: 60000
        keepAlive: true
        validationQuery: SELECT 1 FROM DUAL
        minIdle: 20
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        filters: stat,wall,log4j
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3308/lover?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: master
        password:
        # 配置监控中心显示的datasource名称
        name: slave-datasource
        # 启动程序时，在连接池中初始化多少个连接
        initialSize: 20
        # 连接池中最多支持多少个活动会话
        maxActive: 60
        # 程序向连接池中请求连接时,超过maxWait的值后，认为本次请求失败，即连接池没有可用连接，单位毫秒，设置-1时表示无限等待
        maxWait: 60000
        # 池中某个连接的空闲时长达到 N 毫秒后, 连接池在下次检查空闲连接时，将回收该连接,要小于防火墙超时设置
        minEvictableIdleTimeMillis: 300000
        # 检查空闲连接的频率，单位毫秒, 非正整数时表示不进行检查
        timeBetweenEvictionRunsMillis: 60000
        # 程序没有close连接且空闲时长超过 minEvictableIdleTimeMillis,则会执行validationQuery指定的SQL,以保证该程序连接不会池kill掉,其范围不超过minIdle指定的连接个数。
        keepAlive: true
        # 检查池中的连接是否仍可用的 SQL 语句,drui会连接到数据库执行该SQL, 如果正常返回，则表示连接可用，否则表示连接不可用
        validationQuery: SELECT 1 FROM DUAL
        # 回收空闲连接时，将保证至少有minIdle个连接.
        minIdle: 20
        # 空闲时检测连接是否有效。(高效)
        testWhileIdle: true
        # 程序 申请 连接时,进行连接有效性检查（低效，影响性能）
        testOnBorrow: false
        # 程序 返还 连接时,进行连接有效性检查（低效，影响性能）
        testOnReturn: false
        # 缓存通过以下两个方法发起的SQL:public PreparedStatement prepareStatement(String sql);public PreparedStatement prepareStatement(String sql,int resultSetType, int resultSetConcurrency)
        poolPreparedStatements: true
        # 每个连接最多缓存多少个SQL
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监监控统计: filter:stat;日志监控: filter:log4j 或者 slf4j;防御SQL注入: filter:wall
        filters: stat,wall,log4j
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true
        # 连接属性。比如设置一些连接池统计方面的配置。
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    config:
      masterslave:
        load-balance-algorithm-type: round_robin
        name: dataSource
        master-data-source-name: master
        slave-data-source-names: slave
    props:
      sql.show: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://49.232.136.153:3307/lover?useUnicode=true&amp;characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: lover
      password: lover123
#      url: jdbc:mysql://127.0.0.1:3306/lover?useUnicode=true&amp;characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#      username: root
#      password:
      initial-size: 3
      max-active: 20
      druid.min-idle: 5
      # 监控配置项
      stat-view-servlet:
        enabled: true
        reset-enable: true
        url-pattern: /druid/*
        # allow: 127.0.0.1
        login-username: newtv
        login-password: supernewtv
thymeleaf:
  #开发时关闭缓存,不然没法看到实时页面
  cache: false
  mode: HTML5
  encoding: UTF-8
  servlet:
    content-type: text/html
#thymeleaf end
email:
  author: 3101547952@qq.com
  authPass: acdzlwhkmgskdcgf
  sendto: 498420540@qq.com;2719538200@qq.com
#  sendto: 498420540@qq.com;
#mybatis&&通用Mapper
mybatis:
  type-aliases-package: com.yue.test.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
mapper:
  style: normal
  mappers: com.yue.test.mapper.TKMapper
  identity: MYSQL
commom:
  FilePath:
    weChatRunner: /soft/file/weChatRunner/
    weCharScript: python3  /soft/file/weChatRunner/weixinRun.py